-- AlterTable
ALTER TABLE "Design" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Qrcode" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Quser" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
